### PR TITLE
Add optional parameter 'run_tagged'

### PR DESCRIPTION
**Pull request by EmteZogaf**

### CODE REVIEW

**Comment by cablespaghetti** [comment]
Testing this at the moment.

**Comment by cablespaghetti** [comment]
There are a few minor tweaks required to make this work:
```
@@ -210,12 +210,11 @@ define gitlab_ci_multi_runner::runner (
     }
 
     if $run_untagged != undef {
-        $run_untagged_opt = '--run_untagged'
         if $run_untagged {
-            $run_untagged_opt = "${run_tagged_opt}=true"
+            $run_untagged_opt = "--run-untagged=true"
         }
         else {
-            $run_untagged_opt = "${run_tagged_opt}=false"
+            $run_untagged_opt = "--run-untagged=false"
         }
     }
```

If you make those I'll merge it in. :)

**Comment by cablespaghetti** [comment]
Oh. In fact I can make them myself. Merging.

**Comment by EmteZogaf** [comment]
Thanks for cleanup and merging.

**Pull request merged**
