### PR TITLE
Pass in env vars

### PR DESCRIPTION
**Pull request by edestecd**
You should be able to pass in environment vars like http_proxy etc.

### CODE REVIEW

**Comment by frankiethekneeman** [comment]
This could be useful - could you point me to the documentation/code where you extracted this information so I can educate myself on it?

**Comment by edestecd** [comment]
The environment option is mentioned here:  https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/blob/master/docs/configuration/advanced-configuration.md

I examined the output of:
$ gitlab-ci-multi-runner help register

TO determine that --env was how to set it.

**Comment by edestecd** [comment]
I needed this to work in my environment, as we are behind a corporate web proxy.
I figured giving the full env over just proxy settings would be more useful.

**Comment by frankiethekneeman** [comment]
@edestecd Your build is failing - it seems puppet 2.6.18 doesn't care for your trailing commas.

**Comment by edestecd** [comment]
Hmm, I guess I usually do not test on 2.6.
Do you have a case where puppet is being used at that old of a version?
I could probably remove the trailing commas.  It does not seem like a big deal.

**Comment by edestecd** [comment]
@frankiethekneeman I think that fixes it.

**Pull request merged**
