### PR TITLE
Add support for docker-volume-option, fix recreation of runner on every run

### PR DESCRIPTION
**Pull request by hseffler**
- Add support for docker-volume-option, mostly c&p from similar code for a new option
- fix recreation of runner on every run by using the config-file in the check not the version

Both changes have been tested and work :-)

### CODE REVIEW

**Comment by cablespaghetti** [comment]
Sorry it's taken so long to get to this. I've fixed the conflicts but could you fix the travis build failures?

Thanks

**Comment by hseffler** [comment]
Sorry, did not notice your reply.

Fixed the Travis-CI issues

**Comment by cablespaghetti** [comment]
Looks pretty good now. The only thing is that I would use $theVersion here:
`    if ! ($version in ['latest', 'present']) {`

**Comment by hseffler** [comment]
right

**Pull request merged**
